image: docker:latest
services:
  - docker:dind

stages:
  - build

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

pritunl-docker-build:
  stage: build
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag="latest"
      else
        tag="$CI_COMMIT_REF_SLUG"
      fi
    - docker build --pull -t "$CI_REGISTRY_IMAGE:${tag}" -t "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID" ./
    - docker push "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID"
    - docker push "$CI_REGISTRY_IMAGE:${tag}"
  only:
    - master
    - nossl
