image: docker:latest
services:
  - docker:dind

stages:
  - build

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

pritunl-docker-build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:latest" -t "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID" ./
    - docker push "$CI_REGISTRY_IMAGE:$CI_PIPELINE_ID"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master

    
