#!/bin/sh
set -e

[ -d /dev/net ] ||
    mkdir -p /dev/net
[ -c /dev/net/tun ] ||
    mknod /dev/net/tun c 10 200

touch /var/log/pritunl.log
touch /var/run/pritunl.pid
/bin/rm /var/run/pritunl.pid

## start a local mongodb instance if no mongodb specified through env
if [ -z "$MONGODB_URI" ]; then
  /usr/bin/mongod -f /etc/mongod.conf &
  sleep 70 ## for mongo to allocate journals
  MONGODB_URI="mongodb://localhost:27017/pritunl"
fi

cat << EOF > /etc/pritunl.conf
{
    "debug": false,
    "bind_addr": "0.0.0.0",
    "port": 9700,
    "static_cache": true,
    "log_path": "/var/log/pritunl.log",
    "temp_path": "/tmp/pritunl_%r",
    "local_address_interface": "auto",
    "mongodb_uri": "$MONGODB_URI"
}
EOF

#/usr/bin/pritunl start &
/usr/bin/pritunl set app.reverse_proxy true
/usr/bin/sudo pritunl set app.redirect_server false
/usr/bin/sudo pritunl set app.server_ssl false
/usr/bin/sudo pritunl set app.server_port 9700

/usr/bin/pritunl start --daemon --pidfile /var/run/pritunl.pid
[ "$1" ] && exec "$@"

